version: '2'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ./data:/docker-entrypoint-initdb.d/
 #     - ./tmp:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=world
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbp4ss 
    ports:
      - '3306:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
#  datastore:
#    image: busybox
#    volumes:
#      - /var/lib/mysql