server:
  port: 8888

management:
  context-path: /admin

spring:
  cloud:
    config:
      server:
        git:
          uri: git@git.true.th:omx-config/sms-adapter-config.git
          force-pull: true
