version: '2'

services:
  spring-kafka-app1:
    image: java:8
    volumes:
        - ./spring-kafka-app1.jar:/app/spring-kafka-app1.jar
        - ./app-logs:/app/logs/
    command: java -jar /app/spring-kafka-app1.jar -Xmx768m -Xms512m -Xss4m  -XX:NewSize=256m -XX:MaxNewSize=256m -XX:MaxPermSize=128m -XX:PermSize=128m
    ports:
      - 8081:8080
    environment:
      - logging.level.org.spring=WARN
      - logging.level.org.springframework=WARN
#  datastore:
#    image: busybox
#    volumes:
#      - /var/lib/mysql