version: '2'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    volumes:
      - ./mysql-data:/docker-entrypoint-initdb.d/
      - ./mysql-logs:/var/log
      - ./mysql-conf:/etc/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=world
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbp4ss
    ports:
      - '3306:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
  spring-boot-docker-app1:
    image: java:8
    volumes:
        - ./spring-boot-docker-app1.jar:/app/spring-boot-docker-app1.jar
        - ./app-logs:/app/logs/
    command: java -jar /app/spring-boot-docker-app1.jar -Xmx768m -Xms512m -Xss4m  -XX:NewSize=256m -XX:MaxNewSize=256m -XX:MaxPermSize=128m -XX:PermSize=128m
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8081:8080
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/world
      - spring.datasource.username=root
      - spring.datasource.password=pass
      - logging.level.org.hibernate=WARN
      - logging.level.org.spring=WARN
      - logging.level.org.springframework=WARN
#  datastore:
#    image: busybox
#    volumes:
#      - /var/lib/mysql