version: '2'

services:
  spring-boot-docker-app2:
    image: java:8
    volumes:
        - ./spring-boot-docker-app2.jar:/app/spring-boot-docker-app2.jar
        - ./app-logs:/app/logs/
    command: java -jar /app/spring-boot-docker-app2.jar
    ports:
      - 8082:8080
    environment:
      - logging.level.org.hibernate=WARN
      - logging.level.org.spring=WARN
      - logging.level.org.springframework=WARN