version: '2'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ./data:/docker-entrypoint-initdb.d/
 #     - ./tmp:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=world
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbp4ss 
    ports:
      - '3306:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
  spring-boot-docker:
    image: java:8
    volumes:
        - ./spring-boot-docker.jar:/app/spring-boot-docker.jar
        - ./logs:/app/logs/
    command: java -jar /app/spring-boot-docker.jar
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8081:8080
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/world
      - spring.datasource.username=root
      - spring.datasource.password=pass
      - logging.level.org.hibernate=DEBUG
#  datastore:
#    image: busybox
#    volumes:
#      - /var/lib/mysql